<?xml version="1.0" encoding="utf-8"?>
<?AutomationStudio FileVersion="4.9"?>
<Program SubType="ANSIC" xmlns="http://br-automation.co.at/AS/Program">
  <Files>
    <File Description="Name the suite and add PVs for the program" Private="true">variables.var</File>
    <File>testSuite.c</File>
    <File Description="Auto generated code - list of all test sets in the program">autoGeneratedFile.c</File>
    <File Description="Test set">Set_BrbUaGetAttributeIdDatatype.c</File>
    <File Description="Test set">Set_BrbUaAddBooleanText.c</File>
    <File Description="Test set">Set_BrbUaAddNodeClassText.c</File>
    <File Description="Test set">Set_BrbUaAddDatatypeIdText.c</File>
    <File Description="Test set">Set_BrbUaAddArrayDimensionText.c</File>
    <File Description="Test set">Set_BrbUaAddAccessLevelText.c</File>
    <File Description="Test set">Set_BrbUaAddEventNotifierText.c</File>
  </Files>
</Program>