
TYPE
	Step_TYP : 	STRUCT 
		eStepNr : Steps_ENUM;
		eErrorStep : Steps_ENUM;
		nSubscriptionIndex : INT;
		nItemIndex : INT;
		nErrorId : DWORD;
	END_STRUCT;
	Steps_ENUM : 
		(
		eSTEP_NONE,
		eSTEP_INIT,
		eSTEP_CONNECT,
		eSTEP_CONNECT_WAIT,
		eSTEP_GET_NAMESPACEIDX_ORG,
		eSTEP_GET_NAMESPACEIDX_ORG_WAIT,
		eSTEP_GET_NAMESPACEIDX_BRPV,
		eSTEP_GET_NAMESPACEIDX_BRPV_WAIT,
		eSTEP_CREATE_SUBSCRIPTIONS_VAR,
		eSTEP_CREATE_SUBSCRIPTION_VAR,
		eSTEP_CREATE_SUBSCRIPT_VAR_WAIT,
		eSTEP_SUB_GET_NODE_HDL_LIST,
		eSTEP_SUB_GET_NODE_HDL_LIST_WAIT,
		eSTEP_ADD_MONITORED_ITEMS,
		eSTEP_ADD_MONITORED_ITEMS_WAIT,
		eSTEP_CREATE_SUBSCRIPTION_EVT,
		eSTEP_CREATE_SUBSCRIPT_EVT_WAIT,
		eSTEP_EVT_GET_NODE_HDL,
		eSTEP_EVT_GET_NODE_HDL_WAIT,
		eSTEP_ADD_EVENT_ITEM,
		eSTEP_ADD_EVENT_ITEM_WAIT,
		eSTEP_RD_GET_NODE_HDL_LIST,
		eSTEP_RD_GET_NODE_HDL_LIST_WAIT,
		eSTEP_WR_GET_NODE_HDL_LIST,
		eSTEP_WR_GET_NODE_HDL_LIST_WAIT,
		eSTEP_METH_GET_HANDLES,
		eSTEP_METH_GET_HANDLE,
		eSTEP_METH_GET_HANDLE_WAIT,
		eSTEP_RUNNING,
		eSTEP_PAR_ERROR,
		eSTEP_CONNECTION_ERROR,
		eSTEP_READ_LIST,
		eSTEP_READ_LIST_WAIT,
		eSTEP_WRITE_LIST,
		eSTEP_WRITE_LIST_WAIT,
		eSTEP_CALL_METH_CALC,
		eSTEP_CALL_METH_CALC_WAIT
		);
END_TYPE
